name: Auto-Deploy

on:
  push:
    branches:
      - master

env:
  FTP_HOST: ${{ secrets.IP }}
  FTP_USERNAME: ${{ secrets.USERNAME }}
  FTP_PASSWORD: ${{ secrets.PASSWORD }}
  FTP_PORT: ${{ secrets.PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Cpanel

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build website
      run: npm run build

    - name: Deploy to FTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ env.FTP_HOST }}
        port: ${{ env.FTP_PORT }}
        username: ${{ env.FTP_USERNAME }}
        password: ${{ env.FTP_PASSWORD }}
        local_path: dist
        remote_path: '/home/nixqueco/test.nixque.com'
        sftp_only: true

        