name: Auto-Deploy

on:
  push:
    branches:
      - master

env:
  FTP_SERVER: ${{ vars.SERVER }}
  FTP_USERNAME: ${{ vars.USERNAME }}
  FTP_PASSWORD: ${{ secrets.PASSWORD }}
  FTP_PORT: ${{ vars.PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Cpanel

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build website
      run: npm run build

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ env.FTP_SERVER }}
        port: ${{ env.FTP_PORT }}
        username: ${{ env.FTP_USERNAME }}
        password: ${{ env.FTP_PASSWORD }}
        local-dir: dist
        server-dir: ./
        dangerous-clean-slate: true
        timeout: 60000

        